name: sportboo_mobile_client
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  flutter_hooks: ^0.20.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_multi_formatter: ^2.12.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  http: ^1.1.2
  intl: ^0.18.1
  loading_animation_widget: ^1.2.0+4
  page_transition: ^2.1.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  flutter_smart_dialog: ^4.9.6
  transitioned_indexed_stack: ^1.0.2
  reactive_forms: ^16.1.1
  reactive_phone_form_field: ^2.0.1
  shared_preferences: ^2.2.2
  sticky_headers: ^0.3.0+2
  dio: ^5.4.1
  flutter_switch: ^0.3.2
  credit_card_validator: ^2.1.0
  credit_card_type_detector: ^3.0.0
  get: ^4.6.6

  firebase_core: ^2.27.2
  firebase_messaging: ^14.7.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/svgs/
#   - assets/svgs/livescore/
#   - assets/svgs/wallet/
#   - assets/svgs/p2p/
#   - assets/svgs/profile/
#   - assets/svgs/auth/
   - assets/pngs/
#   - assets/pngs/livescore/
#   - assets/pngs/wallet/
#   - assets/pngs/p2p/
#   - assets/pngs/profile/
#   - assets/pngs/auth/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
